### ISSUE TITLE
How to upgrade Bundler version?

### ISSUE THREAD

**Issue by Qqwy** [pagodabox/nanobox-engine-ruby#40]
This is information currently missing from the README:

Our current Nanobox installation is stuck on bundler 1.16.4. However, bundler 2.x has been out for quite some time. If locally build with the new bundler version, the deployment will break, because the old bundler version in the Nanobox will refuse to use the new `Gemfile.lock`.

Is the bundler version configurable in some way? What versions are supported by `nanobox-engine-ruby`?

I think this information ought to be added to the README. :slightly_smiling_face:

**Comment by danhunsaker** [comment]
This isn't configurable, to my knowledge, because it uses the latest version available in the Nanobox package repository. Which means versions after 1.16.4 aren't available automatically.

Nanobox v2 will be released, soon, and the Nanobox package repository will no longer be needed, which is (I believe) the majority of why the package repository is so far out of date.

**Comment by Qqwy** [comment]
:slightly_frowning_face: :man_shrugging: 

@danhunsaker Thank you for your explanation. We'll make do with the old bundler version for now.
