### ISSUE TITLE
Specify other ruby_runtime

### ISSUE THREAD

**Issue by fnmunhoz** [pagodabox/nanobox-engine-ruby#5]
Hello guys!

I'm experimenting with nanobox and trying to build up an app with ruby `2.2.3`, but I couldn't find a way to specify this version.

I saw the docs says about `ruby-2.2` and it install `ruby '2.2.2'`, but I have ruby `ruby '2.2.3'` on my Gemfile. 

I looked around the code for ways to use another ruby version, and I found that it is using `pkgsrc/pkgin` to manage packages, and looks like pkgsrc has support for ruby 2.2.3 [1].

But unfortunately, I'm not able to just use a version available in pkgsrc.

I tried with this Boxfile:

``` yml
build:
  ruby_runtime: 'ruby22-2.2.3'
```

But `nanobox-engine-ruby` is using another format `ruby-2.2` and I didn't figured out where it is looking for this version.

Is it possible to use another ruby versions? I could try submit a Pull Request if you guys point me the direction.

Awesome project by the way :grinning: 

[1] http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/lang/ruby22/README.html

**Comment by sanderson** [comment]
@fnmunhoz, we use our own pkgsrc for loading runtimes into engines. You can view the available packages here: http://pkgsrc.nanobox.io/nanobox/base/Linux/.

Currently ruby.2.2.2 is the most to-date package avialable, but I've added ruby-2.2.3 to the list of requested runtimes. We're hoping to run through and update all the packages in the next few days.

**Comment by fnmunhoz** [comment]
@sanderson I got that. Thanks for the explanation.

Any reason to reference the version as `ruby-2.2` instead of `ruby-2.2.2` ?

I ask that because, some enviroments like heroku normally reference the most specific version like `1.9.3`, `2.2.2` or `2.2.3`.

**Comment by sanderson** [comment]
You can specify as deep as you'd like. It'll take the most recent version of the depth you specify. For example, If you listed `ruby-1` in your Boxfile, it would use the most recent version of ruby-1.x (`ruby-1.9.3`).

In most cases, functionality is dependent on major and minor versions rather than patch levels. That's why the major and minor version are listed in the docs. But if a specific patch level is needed, you can specify that as well. Just know that if the version is specified all the way to the patch level, when a new patch/version comes out, your app will not automatically update. You'll have to go in and specify the new version.

**Comment by fnmunhoz** [comment]
@sanderson thats cool!

Thanks for the clarification.

**Comment by sanderson** [comment]
@fnmunhoz, ruby-2.2.3 is now available. If you just specify `ruby-2.2` in your Boxfile, it will pull in ruby-2.2.3.

**Comment by fnmunhoz** [comment]
@sanderson thats great, thanks!
